GameSaver/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls',namespace="login")),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('', views.screeninit),
    path('login/home',views.showhome,name='home'),
    path('addgame',views.showaddgame),
    path('newgame',views.newgame)
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    picture = models.ImageField(default='profile_default.png',upload_to='users/')


class Games(models.Model):
    name = models.CharField(max_length=80,blank=False,null=False)
    year = models.IntegerField()
    prize = models.IntegerField()
    image = models.ImageField(upload_to='videogames/',blank=True,null=True)
    storage = models.IntegerField()
    score = models.IntegerField()
    platform = models.CharField(max_length=20,blank=False,null=False)
    E = 'EVERYONE'
    E10 = 'EVERYONE10'
    T = 'TEEN'
    M = 'MATURE'
    A = 'ADULT'
    RATING_CHOICES = [
        (E, 'E'),
        (E10, 'E+10'),
        (T, 'T'),
        (M, 'M'),
        (A, 'A'),
    ]
    rating = models.CharField(
        max_length=12,
        choices=RATING_CHOICES,
        default=E,
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

login/views.py
from django.shortcuts import render
from login.models import Games,User

# Create your views here.


def screeninit(request):
    return render(request,'initscreen.html')

def showhome(request):
    userid = request.user.id
    games = Games.objects.filter(user__id=userid)
    data = {'games':games}
    return render(request,'home.html',data)

def showaddgame(request):
    return render(request,'addgame.html')

def newgame(request):
    if request.method=='POST':
        usercurrent = request.user.id
        namegame = request.POST['namegame'] 
        yeargame = request.POST['year']
        pricegame = request.POST['price']
        try:
            picture = request.FILES['txtfot']
        except:
            picture = "users/profile_default.png"

        storagegame = request.POST['storage']
        scoregame = request.POST['inpscore']
        platgame = ""
        xboxplat=""
        psplat=""
        ninplat=""
        try:
            xboxplat = request.POST['xboxbtn'] 
        except:
            print('error')
        try:
            psplat = request.POST['inpplay'] 
        except:
            print('error')
        try:
            ninplat = request.POST['btnnin']
        except:
            print('error')
        platgame = xboxplat+psplat+ninplat
        rt=""
        r1=""
        r2=""
        r3=""
        r4=""
        r5=""

        try:
            r1 = request.POST['ebtn']
        except:
            print('error')
        try:
            r2 = request.POST['e10btn']
        except:
            print('error')
        try:
            r3 = request.POST['tbtn']
        except:
            print('error')
        try:
            r4 = request.POST['mbtn']
        except:
            print('error')
        try:
            r5 = request.POST['abtn']
        except:
            print('error')

        rt=r1+r2+r3+r4+r5

        usergame = User.objects.get(id=usercurrent)
        game = Games(name=namegame,year=yeargame,prize=pricegame,image=picture,storage=storagegame,score=scoregame,
                     platform=platgame,rating=rt,user=usergame)

        game.save()
        userid = request.user.id
        games = Games.objects.filter(user__id=userid)
        data = {'games':games}
        
        return render(request,"home.html",data)

login/templates/addgame.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Game</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'login/addgame.css' %}" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans&family=Roboto+Condensed&display=swap" rel="stylesheet">
</head>
<body>
    
    <div class="container-fluid">
        <form class="row" method="post" action="/newgame" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-6 mx-auto my-3 col-md-6 " id="colform">
                <label for="name">Name</label>
                <input class="form-control my-1 text-end" type="text" name="namegame" >

                <label for="name">Year</label>
                <input class="form-control my-1 text-center" type="number" value="2023" name="year">

                <label for="name">Price</label>
                <input class="form-control my-1 text-center" type="number" value="0" name="price">

                <label for="name">Image</label>
                <input class="form-control" type="file" id="formFile" name="txtfot">

                <div class="row my-3">
                    <div class="col d-flex align-content-end">
                    <label for="name" class="my-2 mx-3">Storage</label>
                    <input class="form-control my-1 text-center " type="number" value="0" name="storage">
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col d-flex align-content-end">
                    <label for="name" class="my-2 mx-3">Score</label>
                    <input class="form-control my-1 text-center " type="number" value="50" name="inpscore">
                    </div>
                </div>

                <div class="row my-3">
                    <div class="col d-flex justify-content-center">
                        <input type="radio" class="btn-check text-center" name="xboxbtn" id="option1" value="XBOX" >
                        <label class="btn mx-3" for="option1" id="op1">Xbox</label>
                        <input type="radio" class="btn-check" name="inpplay" id="option2" value="PS">
                        <label class="btn mx-3" for="option2" id="op2">PS</label>
                        <input type="radio" class="btn-check text-center" name="btnnin" id="option3" value="Nin" >
                        <label class="btn mx-3" for="option3" id="op3">Nintendo</label>
                    </div>
                </div>

                <div class="row my-3">
                    <div class="col d-flex justify-content-center">
                        <input type="radio" class="btn-check " name="ebtn" id="opt1" value="EVERYONE" >
                        <label class="btn  mx-3" for="opt1"><img src="/media/images/eimg.png" class="img-fluid" > </label>
                        <input type="radio" class="btn-check" name="e10btn" id="opt2" value="EVERYONE10" >
                        <label class="btn mx-3" for="opt2"><img src="/media/images/e10img.png" class="img-fluid" ></label>
                        <input type="radio" class="btn-check " name="tbtn" id="opt3" value="TEEN"  >
                        <label class="btn mx-3" for="opt3"><img src="/media/images/timg.png" class="img-fluid" ></label>
                        <input type="radio" class="btn-check " name="mbtn" id="opt4" value="MATURE" >
                        <label class="btn mx-3" for="opt4"><img src="/media/images/mimg.png" class="img-fluid" ></label>
                        <input type="radio" class="btn-check " name="abtn" id="opt5" value="ADULT" >
                        <label class="btn mx-3" for="opt5"><img src="/media/images/aimg.png" class="img-fluid" ></label>
                    </div>
                </div>

                <div class="row d-flex justify-content-center">
                <button class="btn mx-auto my-3" type="submit" id="btnsubmit" style="background-color: #ec2414; width: 40%; color: white;" >Add</button>
                </div>
            </div>

        </form>
       
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script> 
</html>

login/templates/home.html
{% extends "account/base.html" %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GameSaver</title>
</head>
{% block content %}

<link href="{% static 'login/home.css' %}" rel="stylesheet">
<body>
   
   <!---- HOMEEEEEEEEEEEE

    <h1>{{ user.email }}</h1>


    {% if u %}
    <h1> {{ u }}</h1>

    {% endif %}

    --> 

    

    <nav class="navbar navbar-expand-lg" style="border: none;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">My Games</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
              
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0" >

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/addgame" id="addGame">+ Game</a>
                </li>
                <form class="form-inline my-2 my-lg-0 d-flex">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="searchbtn">Search</button>
                  </form>
             
            </ul>
           
          </div>
        </div>
      </nav>


      {% if games %}


      <div class="row py-3 " style="color: black;">
        {% for game in games%}
        <div class="col-lg-3 px-3 py-3 col-sm-6 text-center"> 
        <img src="/media/{{ game.image }}" class="img-thumbnail" style="width: 13rem; height: 15rem ;">
        <p class="mb-1"> {{ game.name }}</p>
        <div class="row d-flex justify-content-center">
          <div class="col text-center" >
            <p class="mb-1" style="margin-left: 5rem;"> {{ game.year }}</p>
          </div>
          <div class="col text-start" >
            <p class="mb-1" style="margin-right: 3rem;"> {{ game.storage }} GB</p>
          </div>
        </div>
        <p class="mb-1">  $ {{ game.prize }}</p>

        {% if game.score < 50 %}
        <p class="mb-1" style="color: red;"> MetaCritic: {{ game.score }}</p>
        {% elif game.score > 49 and game.score < 60 %}
        <p class="mb-1" style="color: #ec2414;"> MetaCritic: {{ game.score }}</p>
        {% elif game.score > 59 and game.score < 70 %}
        <p class="mb-1" style="color: goldenrod;"> MetaCritic: {{ game.score }}</p>
        {% elif game.score > 69 and game.score < 85 %}
        <p class="mb-1" style="color: #137b13;"> MetaCritic: {{ game.score }}</p>
        {% elif game.score > 84   %}
        <p class="mb-1" style="color: #05519d;"> MetaCritic: {{ game.score }}</p>


        {% endif %}
        <div class="row d-flex justify-content-center">
          <div class="col mx-1 text-end">
        {% if game.platform == "XBOX" %}
        <img src="/media/images/xbox.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
        {% elif game.platform == "PS" %}
        <img src="/media/images/pslogo.jpg" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
        {% elif game.platform == "Nin" %}
        <img src="/media/images/ninlogo.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
        {% endif %}
        </div>
        
          <div class="col text-start">
            {% if game.get_rating == "E" %}
            <img src="/media/images/eimg.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
            {% elif game.get_rating == "E+10" %}
            <img src="/media/images/e10img.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
            {% elif game.get_rating_display == "T" %}
            <img src="/media/images/timg.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
            {% elif game.get_rating == "M" %}
            <img src="/media/images/mimg.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
            {% elif game.get_rating == "A" %}
            <img src="/media/images/aimg.png" class="img-thumbnail" style="width: 4rem; height: 4rem ;">
            {% endif %}
          </div>
          </div>
        </div>
        {% endfor %}

      </div>

      {% else %}
      <div class="row mx-auto text-center" id="rowb" style="background-color: white; color: black;">
       <P> Games Not Found</P>
      </div>


      {% endif %}
</body>
{% endblock %}


</html>

login/templates/initscreen.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GameSaver</title>
    <link rel="icon" type="image/x-icon" href="../media/images/redPandaIcon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'login/initscreen.css' %}" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans&family=Roboto+Condensed&display=swap" rel="stylesheet">
</head>
<body>
 
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static '../media/images/redPandaIcon.png' %}" alt="No Encontrada" width="50" height="50" id="icon"/></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" id="firstitem">GameSaver</a>
              </li> 
              </ul>
              <ul class="navbar-nav ms-auto mb-2 mb-lg-0" >
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="https://www.xbox.com/es-CO" id="xboxitem">XBOX</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="https://www.playstation.com/es-co/" id="psitem">PS</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="https://www.nintendo.com/es-co/" id="nintendoitem">Nintendo</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#" id="signup">Sign Up</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'account_login' %}" id="login">Log In</a>
              </li> 
            </ul>
           
          </div>
        </div>
      </nav>
        
      <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="2000">
            <img src="../media/images/xbox.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <img src="../media/images/ps.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <img src="../media/images/nin.jpg" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

      <section class="container-fluid">
        <div class="row">
            <div class="col">
        <p class="p-4">
            Introducing GameSaver the ultimate website for saving and organizing all your favorite <span>Xbox</span>,<span>PlayStation</span> , and <span>Nintendo</span> game saves in one convenient location.
        </p>
            </div>
            <div class="col">
        <p class="p-4">
            GameSaver is more than just a tool, you can easily sort and categorize your game saves by console, game title, or date. 
        </p>
            </div>
        </div>
      </section>

      <section class="container-fluid" id="rowb">
        <div class="row w-75 mx-auto" >
            <div class="col-lg-6 py-3 ">
                <img class="img-thumbnail" src="../media/images/gameyear.jpg" alt="No Encontrada" id="imagega"/>
            </div>
            <div class="col-lg-6 align-self-center" >
                <p class="py-3"> 
                    GAME OF THE YEAR <br>
                    Elden Ring deliver a unique and immersive gameplay experience. Set in a sprawling open world filled with danger and mystery, players will be able to create their own character and explore a variety of environments</p>
            </div>
        </div>
      </section>
        

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</html>